Final/Final/Controllers/ArtWorkController.cs
using Final.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Final.Controllers
{
    public class ArtWorkController : Controller
    {

        private ArtContext db = new ArtContext();

        // GET: ArtWork
        public ActionResult Index()
        {
            return View(db.ArtWorks.ToList());
        }
    }
}

Final/Final/Controllers/ArtistController.cs
using Final.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Final.Controllers
{
    public class ArtistController : Controller
    {

        private ArtContext db = new ArtContext();

        // GET: Artist
        public ActionResult Index()
        {
            return View(db.Artists.OrderBy(a => a.FirstName).ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var artist = db.Artists.Find(id);

            if (artist == null)
            {
                return HttpNotFound();
            }

            ViewBag.NumOfArt = artist.ArtWorks.Count();

            return View(artist);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Artist artist)
        {
            if (ModelState.IsValid)
            {
                db.Artists.Add(artist);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(artist);
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var artist = db.Artists.Find(id);

            if (artist == null)
            {
                return HttpNotFound();
            }

            ViewBag.FN = artist.FullName;

            return View(artist);
        }

        [HttpPost]
        public ActionResult Edit(Artist newArtist)
        {
            int nameLength = newArtist.FirstName.Length + newArtist.LastName.Length;

            if (ModelState.IsValid && nameLength < 50)
            {
                var oldArtist = db.Artists.Find(newArtist.ID);
                UpdateModel(oldArtist);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = oldArtist.ID });
            }

            if (nameLength > 50)
            {
                ViewBag.Error = 1;
                ViewBag.ErrorMessage = "Artist full name cannot be longer than 50 characters";
            }

            return View(newArtist);
        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var artist = db.Artists.Find(id);

            if (artist == null)
            {
                return HttpNotFound();
            }

            return View(artist);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            Artist artist = db.Artists.Find(id);
            db.Artists.Remove(artist);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Final/Final/Controllers/ClassificationController.cs
using Final.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Final.Controllers
{
    public class ClassificationController : Controller
    {

        private ArtContext db = new ArtContext();

        // GET: Classification
        public ActionResult Index()
        {
            return View(db.Classifications.ToList());
        }
    }
}

Final/Final/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Art Tracker</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Art Tracker", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Artists", "Index", "Artist")</li>
                    <li>@Html.ActionLink("ArtWorks", "Index", "ArtWork")</li>
                    <li>@Html.ActionLink("Classifications", "Index", "Classification")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Cameron Stanavige</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("GenreScripts", required: false)
</body>
</html>